version: '3.5'
services:
    mongodb:
        image: mongo
        restart: always
        container_name: incubator-mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: test
            MONGO_INITDB_DATABASE: incubator
        ports:
            - 27020:27017
        volumes:
            - ./mongodb:/data/db
