@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDBiZGI0OTFmYjU4ZmEwMzBhODM4ODkiLCJpYXQiOjE2Nzg0OTg2NzMsImV4cCI6MTY3ODQ5OTI3M30.MJLUsIZnfYhCdZZGrx31ssh2QOFRz0yKDyY4cegI5VQ

## Регистрация
POST {{baseUrl}}/auth/registration HTTP/1.1
Content-Type: application/json

{
  "login": "224box",
  "password": 123456,
  "email": "224box@mail.ru"
}

###

## Аутентификация
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "loginOrEmail": "224box",
  "password": 123456
}

###

## Обновление токена
POST {{baseUrl}}/auth/refresh-token HTTP/1.1

###

## Активные сессии
GET {{baseUrl}}/security/devices HTTP/1.1

###

## Удалить сессию
DELETE {{baseUrl}}/security/devices/5c522aa5-37ad-465c-8d8a-71ca1c76a4b3 HTTP/1.1

###

## Удалить сессии
DELETE {{baseUrl}}/security/devices HTTP/1.1

###

## Восстановление пароля
POST {{baseUrl}}/auth/password-recovery HTTP/1.1
Content-Type: application/json

{
  "email": "224box@mail.ru"
}
###

## Новый пароль
POST {{baseUrl}}/auth/new-password HTTP/1.1
Content-Type: application/json

{
  "newPassword": "123456",
  "recoveryCode": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YyYWZlMDdlOWQ4MThiZDY0ZDA5NjMiLCJkZXZpY2VJZCI6IjU0NzhiYmFlLTFjZDQtNDU4MC1iZmU3LWJhNGVkODI5MTljYyIsImlhdCI6MTY3Njg0OTEyOSwiZXhwIjoxNjc2ODUwMzI5fQ.xtR8jOOCxZBDL_qd9I1pfZysj_I7l-QPoKy_acHHzPE"
}
###

## Получить пост
GET {{baseUrl}}/posts/640bb6466ca94d2d29c8b053 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
###


## Получить комментарий
GET {{baseUrl}}/comments/640a7ddce36839a503c13a7e HTTP/1.1
Content-Type: application/json
Authorization: {{token}}
###

## Новый комментарий
POST {{baseUrl}}/posts/640a7b108105ac39c2120b08/comments HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "content": "1234sdssfdsfddsdsfd56"
}
###

## Лайк комментария
PUT {{baseUrl}}/comments/640a7ddce36839a503c13a7e/like-status HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "likeStatus": "Like"
}
###

## Лайк поста
PUT {{baseUrl}}/posts/640bd75e74b1ef4ed8474a53/like-status HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "likeStatus": "Like"
}
###